add feature, layers, model, firebase, room, layouts, item cards and other
Sergio994350/SkiMountains pull request #1
Opened 2022-10-10 17:25 UTC by Sergio994350

add feature, layers, model, firebase, room, layouts, item cards, drawable, navigation

2022-10-10 21:06 UTC, NLCodeTeam requested changes

2022-10-10 21:06 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/MainActivity.kt
> +        val db = FirebaseFirestore.getInstance()
Почему это сделано тут ? у FB есть  реализация на корутинах, которую показывали на лекции с data

2022-10-10 21:06 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/network/FirebaseRepository.kt
> +    fun getAllSkiPlacesList() = firebaseServiceInterface.getAllSkiPlacesList()
заюзай корутины для FB

2022-10-10 21:06 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/model/SkiPlace.kt
> +    val skiPlaceId: String = "",
Тебе точно нужно столько полей ? убери все лишнее и оставь только то, что ты используешь в приложении

2022-10-10 21:06 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/DetailFragment.kt
> +class DetailFragment {
убери все пустые классы

2022-10-11 16:10 UTC, Sergio994350 commented on app/src/main/java/com/epicteam1/skimountains/MainActivity.kt
> +        val db = FirebaseFirestore.getInstance()
сорри, не убрал из MainActivity, тестил разные варианты. закоммитил, потом убрал уже. :)

2022-10-11 16:11 UTC, Sergio994350 commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/network/FirebaseRepository.kt
> +    fun getAllSkiPlacesList() = firebaseServiceInterface.getAllSkiPlacesList()
ок

2022-10-11 16:12 UTC, Sergio994350 commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/model/SkiPlace.kt
> +    val skiPlaceId: String = "",
32 поля, многовато, но у разных гор много параметров. можно некоторые объединить.

2022-10-11 16:13 UTC, Sergio994350 commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/DetailFragment.kt
> +class DetailFragment {
Они очень нужны для будущего наполнения. И ссылка в layout должна на них быть

2022-10-19 16:37 UTC, closed without merging