Working app ver 0.3.
Sergio994350/SkiMountains pull request #3
Opened 2022-10-30 15:16 UTC by Sergio994350

Working app ver 0.3. change architecture, add splash, change all layers, get all features work - get all places from Firebase, save all places to local DB, get places from DB, save place to favorites, get details. Add backstack and fix few bugs.

2022-10-31 20:14 UTC, NLCodeTeam requested changes

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/core/Extension.kt
> +    data?.get(Constants.SKIPLACE_ID) as String,
Тебе точно столько прям данных надо? есть ощущение что половину можно убрать

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/core/Extension.kt
> +    val railwayAvailSymb =  if (railwayAvail=="true") "☑" else "☐"
вынести надо хотя бы в константу, а для сравнения railwayAvail=="true" сделать extension

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/local/dao/SkiDao.kt
> +    fun getAllSkiPlaces(): List<SkiPlaceEntity>
Почему не suspend ?

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/local/database/SkiDatabase.kt
> +        operator fun invoke(context: Context) = instance ?: synchronized(LOCK) {
это все лишнее, убрать, а инстансирование БД сделать через DI

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/local/entities/SkiPlaceEntity.kt
> +    val skiPlaceId: String = "",
Проверь еще раз - точно ли тебе нужно столько полей ? все что не нужно выкини

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/repository/SkiPlaceRepositoryImpl.kt
> +            .addOnSuccessListener { documents ->
Очень странно, выше там ты используешь await а тут почему колбеки ?

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/repository/SkiPlaceRepositoryImpl.kt
> +                    if (search == place.regionBig || search == place.nameRus ||
условие непонятное, нужно хотя бы в отдельную переменную вынести с хорошим названием

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/repository/SkiPlaceRepositoryImpl.kt
> +    override suspend fun getSkiPlaceById(skiPlaceId: String) =
а тут вызовы БД с suspend значит выше точно ошибка

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/di/featureSkiPlacesDataModule.kt
> +        Room.databaseBuilder(androidApplication(), SkiDatabase::class.java, Constants.LOCAL_DATABASE_NAME).build()
Вот тут создается все нормально и никакие блокировки с инстансами не нужны

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/usecases/DeleteSkiPlaceUseCase.kt
> +interface DeleteSkiPlaceUseCase {
интерфейсы для UseCase это оверхед, можно без них, но так это не ошибка

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/usecases/SkiPlacesUseCase.kt
> +interface SkiPlacesUseCase {
А вот это странно, у тебя до этого юзкейсы были с одним методом, а тут целый список

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/usecases/implementations/DeleteSkiPlaceUseCaseImpl.kt
> +class DeleteSkiPlaceUseCaseImpl(private val skiPlaceRepository: SkiPlaceRepository) : DeleteSkiPlaceUseCase {
Видишь какой это оверхед сильный ? можно на 10 файлов сократить код, это для репозиториев так нужно делать

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/util/Resource.kt
> +sealed class Resource<T>(
за название лайк, класс Loading можно убрать, он не нужен там

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/adapter/SaveAdapter.kt
> +            name_saved_ski_place.text =
так делать нельзя, ты должен в адаптер передавать уже сформированную строку

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/adapter/SkiPlacesAdapter.kt
> +            name_ski_place.text = "${place.nameRus} ${place.regionRus}"
видишь он ругается? это потому что сюда опять же нужно подкинуть сформированную строку

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/adapter/SkiPlacesAdapter.kt
> +    private var onItemClickListener: ((SkiPlace) -> Unit)? = null
это все убрать, листенер можно прокинуть сразу в конструктор

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/DetailFragment.kt
> +        val skiPlaceArg: String = arguments?.getString(Constants.DETAILS)!!
это плохо написано, это значит что если ты аргумент не получишь, то разрешаешь коду упасть, надо обработать по-другому

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/DetailFragment.kt
> +        btn_play_youtube_details.setOnClickListener {
вообще эта штука должна быть в общей активити и через commands обрабатываться, но пока пусть побудет тут, но потом надо убрать

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/DetailFragment.kt
> +    private lateinit var binding: FragmentDetailBinding
binding в onDestroy нужно занулять

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/HomeFragment.kt
> +        if (startCount <= 1) {
да ну нет конечно, фрагмент сам решает что показывать ?

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/HomeFragment.kt
> +        startCount++
да не, это не серьезно конечно

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/HowToGetFragment.kt
> +            findNavController().apply { popBackStack() }
навигацию потом тоже нужно будет вынести

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/SplashFragment.kt
> +        var startCount = 0
опять это

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/SplashFragment.kt
> +            delay(2000L)
это убрать все и поместить в норм место

2022-10-31 20:14 UTC, NLCodeTeam commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/viewModel/SkiPlaceViewModel.kt
> +    private val _skiPlaceDetailLoaded: MutableLiveData<SkiPlace> = MutableLiveData<SkiPlace>()
на mvvm будете делать?

2022-11-01 13:40 UTC, Sergio994350 commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/core/Extension.kt
> +    data?.get(Constants.SKIPLACE_ID) as String,
Точно надо. уже сделал.

2022-11-01 13:41 UTC, Sergio994350 commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/local/entities/SkiPlaceEntity.kt
> +    val skiPlaceId: String = "",
Все нужно

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/core/Extension.kt
> +    val railwayAvailSymb =  if (railwayAvail=="true") "☑" else "☐"
Поправил.

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/local/dao/SkiDao.kt
> +    fun getAllSkiPlaces(): List<SkiPlaceEntity>
Поправил.

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/local/database/SkiDatabase.kt
> +        operator fun invoke(context: Context) = instance ?: synchronized(LOCK) {
Убрал это, оно там дальше через DI

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/repository/SkiPlaceRepositoryImpl.kt
> +            .addOnSuccessListener { documents ->
Оно вообще не надо. Убрал. Фильтрует по локальной базе.

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/data/repository/SkiPlaceRepositoryImpl.kt
> +    override suspend fun getSkiPlaceById(skiPlaceId: String) =
Поправил.

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/di/featureSkiPlacesDataModule.kt
> +        Room.databaseBuilder(androidApplication(), SkiDatabase::class.java, Constants.LOCAL_DATABASE_NAME).build()
+

2022-11-01 18:07 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/usecases/DeleteSkiPlaceUseCase.kt
> +interface DeleteSkiPlaceUseCase {
Проверял как работает с одним интерфейсом и как со многими, и что оставить не решил

2022-11-01 18:08 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/domain/usecases/SkiPlacesUseCase.kt
> +interface SkiPlacesUseCase {
Это изначальный вариант, не плодить юзкейсы, а все методы в один юзкейс собрать. Смотрел как оно работает и выглядит с кучей, не решил что оставить.

2022-11-01 18:08 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/HomeFragment.kt
> +        if (startCount <= 1) {
убрано

2022-11-01 18:08 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/viewModel/SkiPlaceViewModel.kt
> +    private val _skiPlaceDetailLoaded: MutableLiveData<SkiPlace> = MutableLiveData<SkiPlace>()
Вроде как

2022-11-01 18:09 UTC, kambievbeslan commented on app/src/main/java/com/epicteam1/skimountains/feature_ski_places/presentation/ui/HomeFragment.kt
> +        startCount++
Вообще убрана инициализация

2022-11-02 08:37 UTC, merged